# Generated by Django 3.2.7 on 2023-02-27 17:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Email')),
                ('password', models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(code='nomatch', message=' A valid password MUST contains at least 10 characters, one lowercase letter, one uppercase letter and one of the following characters: !, @, #, ? or ]', regex='^(?=.?[A-Z])(?=.?[a-z])(?=.*?[!@#?\\]^]).{10,}$')], verbose_name='Password')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=255, verbose_name='Message')),
                ('severity', models.CharField(max_length=30, verbose_name='Severity')),
                ('source', models.CharField(max_length=40, verbose_name='Source')),
                ('timestamp', models.DateTimeField(verbose_name='Timestamp')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
