# Generated by Django 3.2.7 on 2023-02-27 17:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(code='nomatch', message=' A valid password MUST contains at least 6 characters, one lowercase letter, one uppercase letter and one of the following characters: !, @, #, ? or ]', regex='^(?=.?[A-Z])(?=.?[a-z])(?=.*?[!@#?\\]^]).{6,}$')], verbose_name='Password'),
        ),
    ]
